kind: pipeline
type: docker
name: juvix-ci

workspace:
  path: /drone/workspace

environment:
  STACK_ROOT: /drone/workspace/.stack

steps:
  - name: restore-cache
    image: meltwater/drone-cache:dev
    settings:
      backend: "s3"
      restore: true
      bucket: juvix-drone-cache
      region: eu-west-1
      cache_key: "volume"
      mount:
        - ./.stack-work
        - ./.stack    
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: aws_access_key_id
      AWS_SECRET_ACCESS_KEY:
        from_secret: aws_secret_access_key
    volumes:
      - name: cache
        path: /tmp/cache

  - name: test-suite
    image: cryptiumlabs/juvix-ci-2
    pull: if-not-exists
    commands:
      - make test
    depends_on:
      - restore-cache

  - name: rebuild-cache
    image: meltwater/drone-cache:dev
    volumes:
      - name: cache
        path: /tmp/cache
    settings:
      backend: "s3"
      bucket: juvix-drone-cache
      region: eu-west-1
      rebuild: true
      cache_key: "volume"
      mount:
        - ./.stack-work
        - ./.stack
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: aws_access_key_id
      AWS_SECRET_ACCESS_KEY:
        from_secret: aws_secret_access_key
    depends_on:
      - test-suite

  - name: check-formatting
    image: cryptiumlabs/juvix-ci-2
    pull: if-not-exists
    failure: fast
    commands:
      - sh ./scripts/check-formatting.sh
    depends_on:
      - rebuild-cache

  - name: check-org-gen
    image: cryptiumlabs/juvix-ci-2
    pull: if-not-exists
    failure: fast
    commands:
      - sh ./scripts/check-org-gen.sh
    depends_on:
      - rebuild-cache

  - name: test-parser
    image: cryptiumlabs/juvix-ci-2
    pull: if-not-exists
    failure: fast
    commands:
      - make test-parser
    depends_on:
      - rebuild-cache

  - name: test-typecheck
    image: cryptiumlabs/juvix-ci-2
    pull: if-not-exists
    failure: fast
    commands:
      - make test-typecheck
    depends_on:
      - rebuild-cache

  - name: test-compile
    image: cryptiumlabs/juvix-ci-2
    pull: if-not-exists
    failure: fast
    commands:
      - make test-compile
    depends_on:
      - rebuild-cache

volumes:
  - name: cache
    host: 
      path: /tmp/cache

trigger:
  event:
    - push

---
kind: secret
name: aws_access_key_id
data: IU7m4OlzqDGZXm+b8B+abO1BuCc2D8Uk06Qc1/kY01kM59QN2JhO9V8teeTWOQkc

---
kind: secret
name: aws_secret_access_key
data: UipX/UrwBx+FBfrcKmVc6bXxyisTdOrdm0yb439oK81tAWmc68elICZMHmr/Kq4WPbp5PkRLtUegRUx42LFWVxH/4iA=
