name: 'Build & test'
runs:
  using: docker
  image: cryptiumlabs/juvix-ci
  steps:
    - name: Build dependencies
      command: stack build -j2 --only-dependencies +RTS -N2 -qg
    - name: Build Juvix
      command: stack build --copy-bins --fast
    - name: Test Juvix
      command: stack test --fast --jobs=1 --test-arguments "--hide-successes --ansi-tricks false" +RTS -N4
