name:                juvix
version:             0.2.0.0
github:              "cwgoes/juvix"
license:             BSD3
homepage:            https://github.com/cwgoes/juvix#readme
synopsis:            Juvix smart contract transpiler & toolkit
category:            Web3
description:         Please see the README on GitHub at <https://github.com/cwgoes/juvix#readme>
author:              Christopher Goes
maintainer:          cwgoes@pluranimity.org
copyright:           2017-2018 Christopher Goes

extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - protolude
  - text
  - mtl
  - containers

default-extensions:
  - NoImplicitPrelude
  - OverloadedStrings
  - NoMonomorphismRestriction
  - RankNTypes
  - LambdaCase
  - UnicodeSyntax
  - GADTs
  - ScopedTypeVariables
  - DeriveGeneric
  - DeriveAnyClass
  - DerivingStrategies
  - FlexibleContexts
  - FlexibleInstances
  - DataKinds
  - GeneralizedNewtypeDeriving
  - DefaultSignatures
  - QuasiQuotes
  - TypeOperators
  - MultiParamTypeClasses

ghc-options:
  - -ferror-spans
  - -Wall
  - -fno-warn-orphans
  - -fno-warn-name-shadowing
  - -j4

#cpp-options:
# - -DOPTIMIZE

library:
  source-dirs: src
  dependencies:
    - idris
  exposed-modules:
    - Juvix
    - Juvix.CodeGen
    - Juvix.Interpreter
    - Juvix.Backends
    - Juvix.Lang
    - Juvix.Utility

executables:
  juvix:
    source-dirs:      app
    main:             Main.hs
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - juvix
      - directory
      - optparse-applicative
      - ansi-wl-pprint
      - raw-strings-qq
      - yaml
      - aeson
      - haskeline
      - gitrev
  idris-codegen-juvix:
    source-dirs:      codegen
    main:             Main.hs
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - juvix

tests:
  juvix-test:
    main:         Spec.hs
    source-dirs:  test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - juvix
      - tasty
      - tasty-hunit
      - temporary
