resolver: lts-12.12
packages:
- .
extra-deps:
- idris-1.3.0
allow-newer: true
setup-info:
  ghcjs:
    source:
      ghcjs-0.2.1.9011008_ghc-8.4.1:
          url: https://github.com/alexanderkjeldaas/ghcjs/releases/download/ghc-8.4.1-rc2/ghcjs.tar.gz
          sha1: 79051ecce5b9d4feaf9107c00178283e062864e1
